### ISSUE TITLE
[UPDATE] Typo in Unit 1, "What is HF?" section.  The word "Danse" should be "Dance"

### ISSUE THREAD

**Issue by PaulForest** [huggingface/making-games-with-ai-course#11]
# What do you want to improve?
There is a typo in Unit 1, "What is HF?" section.
The word "Danse" should be "Dance" 

- Explain the typo/error or the part of the course you want to improve

There is a typo in Unit 1, "What is HF?" section.
The word "Danse" should be "Dance"

The English spelling doesn't seem to include the French spelling.  
https://www.dictionary.com/browse/dance

I assume this will also come up in later places, but I haven't gotten that far yet. :)

# Actual Issue:
In this image:
https://huggingface.co/datasets/huggingface-ml-4-games-course/course-images/resolve/main/en/unit1/unity/models4.jpg
which is used here:
https://github.com/huggingface/making-games-with-ai-course/blob/main/units/en/unit1/what-is-hf.mdx

# **Also, don't hesitate to open a Pull Request with the update**. This way you'll be a contributor of the project.
Sorry, I have no access to the problematic image's source

**Comment by simoninithomas** [comment]
Hi, thanks for pointing this out 🤗
I'm adding it in the next week update.

**Comment by simoninithomas** [comment]
(Finally) updated 🤗
