### ISSUE TITLE
Broken link in `Classical AI in Unity` article

### ISSUE THREAD

**Issue by codekobzar** [huggingface/making-games-with-ai-course#19]
https://github.com/huggingface/making-games-with-ai-course/blob/f3b5f87a31028f64b2a71116f196f69e664b24e3/units/en/unitbonus1/ai-in-unity.mdx?plain=1#L5-L8

Current behavior:
* A broken link is replicated three times.
* `Penny De Byl's AI in Games Course` links to `artificial-intelligence-for-beginners` course.

Expected behavior:
* The broken link should be replaced with the working one: `https://learn.unity.com/course/artificial-intelligence-for-beginners`.
* `AI in Games Course` links to the relevant course (I couldn't find a similar course).

---
Thanks for working on this great course!

**Comment by simoninithomas** [comment]
Hi thanks for pointing this out 🤗 I'm updating it, when merged I'll close the issue.

Thanks again

**Comment by simoninithomas** [comment]
Merged ✅ thanks again

**Comment by codekobzar** [comment]
Looks great, thanks for the quick fix. Look forward to the next project units!
